# Generated by Django 3.2.5 on 2021-07-28 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='chapter',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='verse',
            name='verse',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
